### ISSUE TITLE
Blocks all ingress pages of all addons

### ISSUE THREAD

**Issue by maorcc** [GuyKh/ims-envista-custom-component#10]
### System Health details

My health is good now. Thank you.
However, this bug did not contribute to my health, as it took 3 weeks to identify that all the add-ons were not accessible because of an Integration. I'm wondering what in the integration caused such a disruption.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After installing this integration, all addons pages are empty.
The full description of the issue can be found here:
https://community.home-assistant.io/t/add-ons-page-is-empty/778997
To recover, disable this IMS-Envista integration and restart HA.

### Reproduction steps

1. Install the integration on a system that is based on HA OS.
2. Go to the addons page. See that the page is empty
3. Go to any addon page, and see that it is empty.

Full description can be found here: https://community.home-assistant.io/t/add-ons-page-is-empty/778997

### Debug logs

```text
There are no errors in the core or supervisor logs.
```

**Comment by GuyKh** [comment]
I really have no lead in terms of why this would be happening.

The only thing I'd suspect is the fact that I add a Trace Printout ([see here](https://github.com/GuyKh/py-ims-envista/blob/main/ims_envista/ims_envista.py#L62)) for the `ClientSession`.

**Comment by maorcc** [comment]
Would you like to try removing it, and I will let you know if it fixes the issue?

**Comment by GuyKh** [comment]
@maorcc I'll create a python package for you, you should manually update it in `custom_components/ims_envista/manifest.json` - update `0.1.9` to `0.1.10b0` (you maybe need a `sudo` for that) - and check if this helps

**Comment by maorcc** [comment]
Upgrading to v0.0.8 caused the following error on loading:
```
Error fetching information from https://api.ims.gov.il/v1/envista/stations/45/data//daily - 204, message='Attempt to decode JSON with unexpected mimetype: ', url='https://api.ims.gov.il/v1/envista/stations/45/data//daily'
```

Do notice the double slash character in the URL above.

**Comment by maorcc** [comment]
I also tried updating setting "ims-envista==0.1.10b0"
The integration still fails to load. Now I see the following error in the log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ims_envista/commons.py", line 67, in get
    _verify_response_or_raise(response)
  File "/usr/local/lib/python3.12/site-packages/ims_envista/commons.py", line 48, in _verify_response_or_raise
    raise ImsEnvistaApiClientError(
ims_envista.commons.ImsEnvistaApiClientError: Invalid response from IMS - bad Content-Type: text/html
```

**Comment by GuyKh** [comment]
This means that the IMS API returns a bad response (of HTML).
I start seeing this the last few days, this usually means that this is an rate limiter (i.e. you're retrying very fast).
Try to disable this for a while and try again.

**Comment by maorcc** [comment]
I confirm that the integration works now without any impact on the addons.  Thank you!
I wonder if HA Core / Supervisor can protect itself from such issues in integrations. will you report it in the community forum?
Also, can the integration handle the rate limit better?

**Comment by GuyKh** [comment]
Hmmmm... Unsure.
I'm not 100% sure how failing integration initialization is treated in terms of retry etc.

Best thing to do, IMHO, is an increasing retry buffer - i.e. 1 sec, 1 sec, 2 sec, 5 sec, 10 sec, 30 sec, 60 sec, 5 min, 10 min, ....

**Comment by maorcc** [comment]
@GuyKh, we can close this issue. 

Do you have any additional information to add to the forum at https://community.home-assistant.io/t/add-ons-page-is-empty/778997/3?
It can help people identify similar future integration issues. Additionally, a member of the Core team could implement a fix to prevent such problems caused by future integration bugs.
