### ISSUE TITLE
Unknown Error when filling a token

### ISSUE THREAD

**Issue by yakeer** [GuyKh/ims-envista-custom-component#28]
## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.62-haos-raspi
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4988
Installed Version | 2.0.1
Stage | running
Available Repositories | 1560
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 116.8 GB
disk_used | 11.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.16.0), File editor (5.8.0), AirCast (4.2.3), Mosquitto broker (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 5, 2024 at 7:27 AM
-- | --
current_recorder_run | December 20, 2024 at 5:09 PM
estimated_db_size | 557.55 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 1.0.6
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Got an Unknown error.
Logs showing:

![image](https://github.com/user-attachments/assets/3bcdf95e-6d2a-4864-8c46-80075a1007b5)

### Reproduction steps

1. Got a token from the authorities.
2. Put the token in the wizard.
3. Got an unknown error.

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.ims_envista
Source: custom_components/ims_envista/config_flow.py:111
integration: IMS Envista (documentation, issues)
First occurred: 5:24:44 PM (1 occurrences)
Last logged: 5:24:44 PM

Something really wrong happened! https://api.ims.gov.il/v1/envista/stations Invalid response from IMS - bad Content-Type: text/html; charset=utf-8
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/ims_envista/commons.py", line 69, in get
    _verify_response_or_raise(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ims_envista/commons.py", line 50, in _verify_response_or_raise
    raise ImsEnvistaApiClientError(
        msg,
    )
ims_envista.commons.ImsEnvistaApiClientError: Invalid response from IMS - bad Content-Type: text/html; charset=utf-8

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ims_envista/config_flow.py", line 111, in async_step_user
    stations = await self._test_token(
               ^^^^^^^^^^^^^^^^^^^^^^^
        token=token,
        ^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/ims_envista/config_flow.py", line 100, in _test_token
    return await client.get_all_stations_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ims_envista/ims_envista.py", line 234, in get_all_stations_info
    response = await get(session=self._session, url=get_url, token=self._token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ims_envista/commons.py", line 87, in get
    raise ImsEnvistaApiClientError(
        msg,
    ) from exception
ims_envista.commons.ImsEnvistaApiClientError: Something really wrong happened! https://api.ims.gov.il/v1/envista/stations Invalid response from IMS - bad Content-Type: text/html; charset=utf-8
```

**Comment by GuyKh** [comment]
It's IMS returns bad response.

I'll double check but you should retry couple of times with sometime between
